version: 0.2

phases:
  install:
#    runtime-versions:
#      docker: 19
    commands:
      - echo Installing kubectl...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin
      - kubectl version --short --client
      - echo Installing AWS IAM Authenticator...
      - curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mv ./aws-iam-authenticator /usr/local/bin

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo  aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 345594605580.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t demo-app-repo .
      - docker tag demo-app-repo:latest 345594605580.dkr.ecr.us-east-1.amazonaws.com/demo-app-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 345594605580.dkr.ecr.us-east-1.amazonaws.com
      - docker images
      - docker push 345594605580.dkr.ecr.us-east-1.amazonaws.com/demo-app-repo:latest
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region us-east-1 --name mycluster
      - kubectl config current-context
      - kubectl get nodes
      - echo Deploying to Kubernetes cluster...
      - kubectl apply -f k8s-deployment.yml
      - kubectl replace --force -f k8s-deployment.yml
      - kubectl get deployment
  
